### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/forker#1]
- [ ] use `github-readme`
- [x] maintain: pull from upstream .. or delete fork and fork again?
  - https://help.github.com/articles/syncing-a-fork/
  - https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/ :point_left:

**Comment by dkhamsing** [comment]
- [ ] process more than one url in config.yml
